# NumPy
Es de las mejores librerías para arrays

In [1]:
# Importar la libreria y asignarle un alias
import numpy as np

In [2]:
# Crear una lista de forma normal
L1 = [1,2,3,4,5,6,7,8]

In [3]:
# Convertir una lista a una matriz de 1xN 
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# Convertir una lista a un array float
x2 = np.array(L1, dtype='float32')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

## Tipos de dtype
- bool_
- int_, intc, intp, int8, int16, int32, int64
- unit8, uint16, uint32, uint64
- float_, float16, float32, float64
- complex_, complex64, complex128

In [5]:
# Crear una matriz de 3x4 ceros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Crear una matriz de 3x4 unos
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Crear un array de números entre 0 y 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Crear un array de números entre 3 y 11
np.arange(3,12,dtype='float64')

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
# Crear un array de números entre 4 y 5 de 0.1 en 0.1
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [10]:
# Crear un array de números entre 1 y 7 de longitud 12
np.linspace(1.,7.,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [11]:
# Matriz diagional de 5x5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Cambiar la distribución de una matriz
x = np.zeros((8,3))
x.reshape((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Aplanar un vector de datos a 1xN. Esto se aplica a x
x = np.array([[1,2,3,4], [5,6,7,8]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
# Copia del array en una dimensión. Esto no se aplica a x
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# Invertir columnas por filas
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [16]:
# Genera un array de datos indicado con los valores de otro array 
# y si este es mayor se sigue rellenando volviendo a introducir los datos
np.resize(x, (5,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz de 4x4 con los valores desde 0 hasta 15
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matriz 5x4
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme

In [17]:
# 1. Crear un array de datos con valores entre 5 y 120.
np.arange(5,121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [18]:
# 2. Crear una matriz de 4x4 con los valores desde 0 hasta 15
M1 = np.arange(0,16)
M1 = np.resize(M1, (4,4))
M1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
# 3. Crear la identidad 7x7
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [20]:
# 4. Crear un array de 20 elementos y transformarlos en una matriz 5x4
A1 = np.arange(20)
A1 = np.resize(A1, (5,4))
A1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
# 5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme
A1 = np.linspace(0,5,20)
A1

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Propiedades de los Array

In [23]:
x = np.arange(12)
x = x.reshape((3,4))
# Dimensiones (Numeros de ejes de una matriz)
x.ndim

2

In [24]:
# Ver cuales son las dimensiones
x.shape

(3, 4)

In [25]:
# Ver el tamaño de la matriz (n*m)
x.size

12

In [27]:
# Ver el tipo de datos de la matriz
x.dtype

dtype('int32')

In [28]:
# Tamaño en bytes de cada uno de los elementos de la matriz
x.itemsize

4

In [29]:
# Buffer de los elementos que contiene la matriz
x.data

In [30]:
# Seleccionar la fila de una matriz
x[2]

array([ 8,  9, 10, 11])

In [34]:
# Seleccionar el elemnto de una matriz
x[2,1]

9

In [36]:
# Obtener la fila 1-2 y la columna 2-3
x[0:2,2:4]

array([[2, 3],
       [6, 7]])

In [37]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [38]:
# Crear una condición para mostrar los elementos
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [39]:
# Crear un array con las condiciones
cond = x < 25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [40]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
# Asignar un número a un conjunto de elementos
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Copias y vistas de Arrays

In [51]:
# CASO 1: Asignación --> No se crea un copia sino una REFERENCIA
x = np.arange(10)
y = x
# Al cambiar el valor de y también se cambia la x
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
y is x

True

In [54]:
# CASO 2: Copia --> Se crea un copia
z = x.copy()
z is x

False

In [56]:
# CASO 3: Vista --> Cambia la vista pero no el contenido del objeto
t = x.view()
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [57]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
t is x

False

In [59]:
t[1:5] = 1

In [60]:
t

array([[0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [61]:
x

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])