# NumPy
Es de las mejores librerías para arrays

In [1]:
# Importar la libreria y asignarle un alias
import numpy as np

In [2]:
# Crear una lista de forma normal
L1 = [1,2,3,4,5,6,7,8]

In [3]:
# Convertir una lista a una matriz de 1xN 
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# Convertir una lista a un array float
x2 = np.array(L1, dtype='float32')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

## Tipos de dtype
- bool_
- int_, intc, intp, int8, int16, int32, int64
- unit8, uint16, uint32, uint64
- float_, float16, float32, float64
- complex_, complex64, complex128

In [5]:
# Crear una matriz de 3x4 ceros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Crear una matriz de 3x4 unos
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Crear un array de números entre 0 y 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Crear un array de números entre 3 y 11
np.arange(3,12,dtype='float64')

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
# Crear un array de números entre 4 y 5 de 0.1 en 0.1
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [10]:
# Crear un array de números entre 1 y 7 de longitud 12
np.linspace(1.,7.,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [11]:
# Matriz diagional de 5x5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Cambiar la distribución de una matriz
x = np.zeros((8,3))
x.reshape((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Aplanar un vector de datos a 1xN. Esto se aplica a x
x = np.array([[1,2,3,4], [5,6,7,8]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
# Copia del array en una dimensión. Esto no se aplica a x
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# Invertir columnas por filas
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [16]:
# Genera un array de datos indicado con los valores de otro array 
# y si este es mayor se sigue rellenando volviendo a introducir los datos
np.resize(x, (5,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz de 4x4 con los valores desde 0 hasta 15
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matriz 5x4
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme

In [17]:
# 1. Crear un array de datos con valores entre 5 y 120.
np.arange(5,121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [18]:
# 2. Crear una matriz de 4x4 con los valores desde 0 hasta 15
M1 = np.arange(0,16)
M1 = np.resize(M1, (4,4))
M1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
# 3. Crear la identidad 7x7
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [20]:
# 4. Crear un array de 20 elementos y transformarlos en una matriz 5x4
A1 = np.arange(20)
A1 = np.resize(A1, (5,4))
A1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
# 5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme
A1 = np.linspace(0,5,20)
A1

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Propiedades de los Array

In [22]:
x = np.arange(12)
x = x.reshape((3,4))
# Dimensiones (Numeros de ejes de una matriz)
x.ndim

2

In [23]:
# Ver cuales son las dimensiones
x.shape

(3, 4)

In [24]:
# Ver el tamaño de la matriz (n*m)
x.size

12

In [25]:
# Ver el tipo de datos de la matriz
x.dtype

dtype('int32')

In [26]:
# Tamaño en bytes de cada uno de los elementos de la matriz
x.itemsize

4

In [27]:
# Buffer de los elementos que contiene la matriz
x.data

In [28]:
# Seleccionar la fila de una matriz
x[2]

array([ 8,  9, 10, 11])

In [29]:
# Seleccionar el elemnto de una matriz
x[2,1]

9

In [30]:
# Obtener la fila 1-2 y la columna 2-3
x[0:2,2:4]

array([[2, 3],
       [6, 7]])

In [31]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
# Crear una condición para mostrar los elementos
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [33]:
# Crear un array con las condiciones
cond = x < 25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [34]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
# Asignar un número a un conjunto de elementos
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Copias y vistas de Arrays

In [36]:
# CASO 1: Asignación --> No se crea un copia sino una REFERENCIA
x = np.arange(10)
y = x
# Al cambiar el valor de y también se cambia la x
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
y is x

True

In [38]:
# CASO 2: Copia --> Se crea un copia
z = x.copy()
z is x

False

In [39]:
# CASO 3: Vista --> Cambia la vista pero no el contenido del objeto
t = x.view()
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
t is x

False

In [42]:
t[1:5] = 1

In [43]:
t

array([[0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [44]:
x

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Funciones Universales (ufunc)
- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimum

In [45]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [48]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [49]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [50]:
alpha = np.linspace(0,2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [51]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [52]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [53]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [54]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [55]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [56]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [57]:
np.sum(x)

45

In [58]:
# Si hay NA los elimina
np.nansum(x)

45

In [59]:
np.mean(x)

4.5

In [60]:
np.median(x)

4.5

In [61]:
np.min(x)

0

In [62]:
np.max(x)

9

In [64]:
# Desviación típica
np.std(x)

2.8722813232690143

In [65]:
# Varianza
np.var(x)

8.25

In [66]:
# Posición del valor minimo
np.argmin(x)

0

In [67]:
# Posición del valor maximo
np.argmax(x)

9

In [68]:
# Percentil
np.percentile(x, q=0.95)

0.08549999999999999

In [69]:
# Si algo tiene True (En este caso al ser matriz si hay algun 0)
np.any(x)

True

In [72]:
# Si todos son True (En este caso al ser matriz si son todos 0)
np.all(x)

False

In [74]:
# Generar valores random
z = np.random.random((3,5))
z

array([[0.98156411, 0.26528388, 0.27999692, 0.29415862, 0.01626758],
       [0.11355393, 0.41837442, 0.49291679, 0.96899352, 0.55075026],
       [0.28479532, 0.45324143, 0.37947134, 0.33629406, 0.25562546]])

In [76]:
z.sum()

6.091287623306611

In [77]:
# Hacer la suma por columnas
z.sum(axis=0)


array([1.37991336, 1.13689973, 1.15238505, 1.5994462 , 0.82264329])

In [78]:
# Hacer la suma por filas
z.sum(axis=1)

array([1.83727111, 2.54458891, 1.7094276 ])

In [80]:
# Semilla aleatoria con la misma secuencia de semilla
np.random.seed(2021)
z = np.random.random((3,5))
z

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013],
       [0.0968944 , 0.05857129, 0.96239599, 0.61655744, 0.08662996]])