# Matrices

In [14]:
import numpy as np

In [15]:
row = [1,2,3]
row

[1, 2, 3]

In [16]:
col = [[1],[2],[3]]
col

[[1], [2], [3]]

In [17]:
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [38]:
# Obtener una fila
M[0]

[1, 2, 3]

In [39]:
# Obtener una columna
for row in M:
    print(row[0])

1
4
7


In [18]:
# Segunda fila segunda columna
M[1][1]

5

In [24]:
A = np.array([[3,0], [1,-1]])
B = np.array([[1,2], [2,9]])
# Multiplicar matrices
A.dot(B)

array([[ 3,  6],
       [-1, -7]])

In [26]:
# Obtener la traspuesta
A.transpose()

array([[ 3,  1],
       [ 0, -1]])

In [27]:
# Obtener la traza de la matriz
A.trace()

2

In [28]:
# Rango de la matriz
np.linalg.matrix_rank(A)

2

In [29]:
# Elevar una matriz a 5
np.linalg.matrix_power(A, 5)

array([[243,   0],
       [ 61,  -1]])

In [30]:
# Obtener el determinante
np.linalg.det(A)

-3.0000000000000004

In [32]:
# Funcion inversa
np.linalg.inv(A)

array([[ 0.33333333,  0.        ],
       [ 0.33333333, -1.        ]])

In [33]:
# Obtener la matriz identidad
np.linalg.inv(A).dot(A)

array([[1., 0.],
       [0., 1.]])

In [34]:
# Matriz no invertible
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.linalg.inv(X)

In [40]:
# No se nos ocurrirá nunca hacer la inversa ni de una matriz cuadrada, ni de una matriz cuyo rango sea inferior a su orden
# (filas / columnas)
# Error: np.linalg.inv(np.array([[1,2,3],[4,5,6]]))